name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run final tests
      run: |
        pytest tests/ -v --cov=main --cov-report=term-missing

    - name: Build Docker image
      run: |
        docker build -t whatsapp-bot:${{ github.sha }} .
        docker tag whatsapp-bot:${{ github.sha }} whatsapp-bot:latest

    - name: Deploy to server
      run: |
        echo "Deploying version ${{ github.sha }} to production"
        # Aquí irían los comandos de despliegue específicos
        # Por ejemplo: kubectl apply, docker push, etc.

    - name: Health check
      run: |
        echo "Performing health check..."
        # Comandos para verificar que el despliegue fue exitoso
        sleep 30
        curl -f http://localhost:8000/health || exit 1

    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Deployment successful!"
        # Aquí podrías agregar notificaciones (Slack, Discord, etc.)

    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        # Aquí podrías agregar notificaciones de error 